[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps =
    alfredosystems/AlfredoCRSF

[env:lolin_s2_mini]
board = lolin_s2_mini
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1 ; Serial = USB CDC on boot (TinyUSB, ESP32-S2)

[env:esp32_wroom_32]
board = esp32dev
; Serial = UART0 via USB-UART bridge chip (CP2102 / CH340).
; DTR forwarding in passthrough unavailable — bridge chip owns the pin.
